# Generated by Django 2.2.1 on 2019-08-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialogue',
            name='answer_nbr',
        ),
        migrations.AddField(
            model_name='dialogue',
            name='answers',
            field=models.ManyToManyField(to='game.Answer'),
        ),
    ]
